'use client'

export { OverviewTab } from './overview'
export { UsersTab } from './users'
export { SuspendedUsersTab } from './suspended'
export { EnrollmentsTab } from './enrollments'
export { CourseRegistrationsTab } from './course-registrations'
export { ContactMessagesTab } from './contact'
export { CoursesTab } from './courses'
export { CommentsTab } from './comments'
export { FaqTab } from './faq'
export { HeroContentTab } from './hero-content'
export { SettingsTab } from './settings'
export { StudentCoursesTab } from './student-courses'

// Nested folders (already have their own index.ts)
export { PaymentsTab } from './payments'
export { BankCardsTab } from './bankcards'
export { InstructorTab } from './instructor'
export { ModulesTab } from './modules'
