export { CourseDescription } from './CourseDescription'
export { CourseHero, type CourseHeroData } from './CourseHero'
export { CourseInstructors, type Instructor } from './CourseInstructors'
export { CourseModulesList, type VideoItem, type ModuleWithVideos } from './CourseModulesList'
export { CourseRequirements } from './CourseRequirements'
export { CourseSidebar } from './CourseSidebar'
export { CourseSyllabus } from './CourseSyllabus'
export { VideoModulesList } from './VideoModulesList'
export { VideoPlayerModal } from './VideoPlayerModal'
export { VideoThumbnail } from './VideoThumbnail'
export { WhatYouLearn } from './WhatYouLearn'
